name: bioinfo_exc
channels:
  - r
  - bioconda
dependencies:
  - r
  - rstudio
  - r-ggplot2
  - r-pheatmap
  - r-factoextra 
  - bioconductor-enhancedvolcano
  - r-plotly
  - r-htmlwidgets
  - bioconductor-biobase
  
